[package]
name = "ecc-kernel"
version = "0.1.0"
edition = "2021"
license = "MIT"

[[bin]]
name = "ecc-kernel"
path = "src/main.rs"

[dependencies]
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.134"
time = { version = "0.3.36", features = ["formatting"] }

